---
# See https://pre-commit.com for more information
default_language_version:
  python: python3.8

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
      # Might make sense once everything is at Python 3
      # - id: check-ast
      - id: check-added-large-files
        args:
          - '--maxkb=1024'
      - id: debug-statements
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: check-docstring-first
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.247'
    hooks:
      - id: ruff
        args:
          - '--fix'
  - repo: 'https://github.com/psf/black'
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pdm-project/pdm
    rev: 2.4.5 # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check
